trigger:
  branches:
    include:
      - main  

pr:
  - '*'

stages:
  - stage: Frontend
    jobs:
      - job: BuildAndRunFrontend
        displayName: 'Build and Run Frontend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
              cd frontend
              npm install
              npm run build
            displayName: 'Install and Run Frontend'

  - stage: Backend
    jobs:
      - job: BuildAndRunBackend
        displayName: 'Build and Run Backend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
              cd backend
              npm install
              npm run build
            displayName: 'Install and Run Backend'