trigger:
  branches:
    include:
      - main  

pr:
  - '*'

stages:
  - stage: Frontend
    jobs:
      - job: BuildAndRunFrontend
        displayName: 'Build and Run Frontend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
              cd frontend
              npm install
            displayName: 'Install Frontend Dependencies'

          - script: |
              cd frontend
              npm run test
            displayName: 'Run Frontend Tests'

          - script: |
              cd frontend
              npm run build
            displayName: 'Build Frontend'

  - stage: Backend
    jobs:
      - job: BuildAndRunBackend
        displayName: 'Build and Run Backend'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '14.x'
            displayName: 'Install Node.js'

          - script: |
              cd backend
              npm install
              
              # Health check script
              npm run start &           
              sleep 5                   
              curl http://localhost:3000  
              pkill -f "node index.js"  
            displayName: 'Health Check Backend'
